#!/bin/sh

#============================================
#-------------- AUTOSTART
#============================================
~/.fehbg &
killall picom
picom &
pgrep -x sxhkd > /dev/null || sxhkd &
#polybar eDP 2>&1 | tee -a /tmp/polybar.log & disown
killall polybar
polybar eDP &
polybar HDMI &
#============================================
# ------------- MONITORS
#============================================

bspc monitor eDP -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 5 6 7 9 

#============================================
#-------------- WINDOW SETTINGS
#============================================

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          28
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

#============================================
#-------------- GLOBAL SETTINGS
#============================================

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
 
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

#============================================
#--------------- RULES
#============================================

#kill previous rule
bspc rule -r "*"
#Fullscreen applications
#bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a rofi state=floating sticky=on

#open applications on specific workspaces
#bspc rule -a Firefox desktop='^1' follow=on

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)

